name: Build Flatpak

on:
  push:
    branches: [main]
  pull_request:
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: eve-influence-map.flatpak
        manifest-path: cloud.pulfer.EveInfluenceMap.yml
        cache-key: flatpak-builder-${{ github.sha }}
    - name: Upload Flatpak artifact
      uses: actions/upload-artifact@v4
      with:
        name: eve-influence-map.flatpak
        path: eve-influence-map.flatpak