name: Build Flatpak

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: eve-influence-map.flatpak
          manifest-path: cloud.pulfer.EveInfluenceMap.yml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: eve-influence-map.flatpak
          path: eve-influence-map.flatpak

      - name: Delete existing 'latest' tag (local and remote)
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch --prune --unshallow || true
          git tag -d latest || true
          git push origin :refs/tags/latest || true

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          name: "Latest Flatpak Release"
          tag_name: latest
          prerelease: false
          files: eve-influence-map.flatpak
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
